{% set version = "1.7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cftime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/CFtime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/CFtime/CFtime_{{ version }}.tar.gz
  sha256: cf067bc60bc9213ff4d9533cdc9ce0fae9d1ffe05c31daf1eedb3e2547b3b4d5

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
  run:
    - r-base
    - r-r6

test:
  commands:
    - $R -e "library('CFtime')"           # [not win]
    - "\"%R%\" -e \"library('CFtime')\""  # [win]

about:
  home: https://github.com/pvanlaake/CFtime
  license: MIT
  summary: Support for all calendars as specified in the Climate and Forecast (CF) Metadata Conventions for climate and forecasting data. The CF Metadata Conventions is widely used for distributing files with climate observations or projections, including the Coupled Model Intercomparison Project (CMIP) data used by climate
    change scientists and the Intergovernmental Panel on Climate Change (IPCC). This package specifically allows the user to work with any of the CF-compliant calendars (many of which are not compliant with POSIXt). The CF time coordinate is formally defined in the CF Metadata Conventions document available at <https://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#time-coordinate>.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
